import argparse
import json
import math
import re
import sys
from pathlib import Path
from types import SimpleNamespace
from typing import Any

from filter_kb_by_progress import load_jsonl, resolve_max_order
from kb_semantic_retriever import DEFAULT_EMBEDDING_MODEL, build_or_load_index, semantic_search


ENGLISH_TOKEN_RE = re.compile(r"[a-zA-Z][a-zA-Z0-9_+#.-]{1,}")
CHINESE_SEGMENT_RE = re.compile(r"[\u4e00-\u9fff]{2,}")
SENTENCE_SPLIT_RE = re.compile(r"[。！？；;!?\n]+")
CHINESE_STOPWORDS = {
    "我们",
    "你们",
    "他们",
    "这个",
    "那个",
    "因为",
    "所以",
    "如果",
    "然后",
    "就是",
    "可以",
    "需要",
    "通过",
    "进行",
    "其中",
    "一个",
    "一种",
    "一些",
    "以及",
    "或者",
    "但是",
    "并且",
    "首先",
    "其次",
    "最后",
    "学生",
    "老师",
    "答案",
    "问题",
    "内容",
    "相关",
}


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Assess answer credibility using ordered textbook KB, semantic retrieval, and optional AI rate."
    )
    parser.add_argument("answer", nargs="?", help="Path to an answer text file. If omitted, use --text.")
    parser.add_argument("--text", default=None, help="Inline answer text.")
    parser.add_argument("--question", default=None, help="Optional question text.")
    parser.add_argument("--kb-dir", default="test/textbook_kb", help="Directory generated by textbook_to_kb.py.")
    parser.add_argument("--max-order", type=int, default=None, help="Use textbook chunks up to this order.")
    parser.add_argument("--chapter", default=None, help='Progress bound chapter, e.g. "第二章 算法与程序实现".')
    parser.add_argument("--section", default=None, help="Optional section bound inside the chosen chapter.")
    parser.add_argument("--semantic-model", default=DEFAULT_EMBEDDING_MODEL, help="Embedding model name.")
    parser.add_argument("--rebuild-index", action="store_true", help="Force rebuild the semantic index.")
    parser.add_argument("--semantic-top-k", type=int, default=12, help="How many semantic candidates to score.")
    parser.add_argument("--report-top-k", type=int, default=5, help="How many evidence chunks to include in report.")
    parser.add_argument("--ai-rate", type=float, default=None, help="Optional AI probability in [0, 1].")
    parser.add_argument("--copyleaks-json", default=None, help="Path to saved Copyleaks JSON response.")
    parser.add_argument(
        "--run-copyleaks",
        action="store_true",
        help="Run Copyleaks detection directly on the answer text and use summary.ai as ai-rate.",
    )
    parser.add_argument(
        "--copyleaks-save-json",
        default=None,
        help="Optional path to save the Copyleaks response when --run-copyleaks is used.",
    )
    parser.add_argument("--save-json", default=None, help="Optional path to save the assessment result as JSON.")
    parser.add_argument("--save-report", default=None, help="Optional path to save a Markdown report.")
    parser.add_argument("--llm-model", default=None, choices=("qwen", "deepseek"), help="Optional LLM report summary.")
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    answer_text = load_answer_text(args)
    if not answer_text.strip():
        raise SystemExit("Answer text is empty.")

    root = Path(__file__).resolve().parents[1]
    kb_dir = (root / args.kb_dir).resolve()
    chunks = load_jsonl(kb_dir / "kb_chunks.jsonl")
    outline = json.loads((kb_dir / "outline.json").read_text(encoding="utf-8"))

    max_order = resolve_max_order(args, chunks, outline)
    in_scope_chunks = [chunk for chunk in chunks if chunk["order"] <= max_order]
    future_chunks = [chunk for chunk in chunks if chunk["order"] > max_order]

    semantic_index = build_or_load_index(
        kb_dir=kb_dir,
        model_name=args.semantic_model,
        force_rebuild=args.rebuild_index,
    )

    ai_rate, ai_source, copyleaks_payload = resolve_ai_rate(args, answer_text=answer_text)
    result = assess_credibility(
        answer_text=answer_text,
        question_text=args.question,
        in_scope_chunks=in_scope_chunks,
        future_chunks=future_chunks,
        semantic_index=semantic_index,
        ai_rate=ai_rate,
        ai_source=ai_source,
        top_k=args.semantic_top_k,
        report_top_k=args.report_top_k,
        max_order=max_order,
    )

    print_summary(result)
    if args.save_json:
        save_json(Path(args.save_json), result)
    if args.save_report:
        report_path = Path(args.save_report)
        report_text = build_teacher_report(
            result=result,
            answer_text=answer_text,
            question_text=args.question,
            llm_model=args.llm_model,
        )
        save_text(report_path, report_text)
    if args.run_copyleaks and args.copyleaks_save_json and copyleaks_payload is not None:
        save_json(Path(args.copyleaks_save_json), copyleaks_payload)

    print("\nRaw assessment:")
    print(json.dumps(result, ensure_ascii=False, indent=2))
    return 0


def load_answer_text(args: argparse.Namespace) -> str:
    if args.text is not None:
        return args.text
    if args.answer:
        return Path(args.answer).read_text(encoding="utf-8")
    return ""


def resolve_ai_rate(args: argparse.Namespace, *, answer_text: str) -> tuple[float | None, str | None, dict[str, Any] | None]:
    if args.ai_rate is not None:
        return clamp(args.ai_rate, 0.0, 1.0), "manual", None

    if args.copyleaks_json:
        payload = json.loads(Path(args.copyleaks_json).read_text(encoding="utf-8"))
        ai_rate = extract_ai_rate_from_copyleaks(payload)
        return ai_rate, "copyleaks_json", payload

    if args.run_copyleaks:
        payload = run_copyleaks_detection(answer_text)
        ai_rate = extract_ai_rate_from_copyleaks(payload)
        return ai_rate, "copyleaks_live", payload

    return None, None, None


def run_copyleaks_detection(answer_text: str) -> dict[str, Any]:
    from copyleaks_code_ai_detector_test import MIN_TEXT_LENGTH, detect_ai, login
    import os

    email = os.getenv("COPYLEAKS_EMAIL")
    api_key = os.getenv("COPYLEAKS_API_KEY")
    if not email or not api_key:
        raise SystemExit("COPYLEAKS_EMAIL and COPYLEAKS_API_KEY are required for --run-copyleaks")

    text = answer_text
    if len(text) < MIN_TEXT_LENGTH:
        repeat = math.ceil(MIN_TEXT_LENGTH / max(len(text), 1))
        text = "\n".join(answer_text for _ in range(repeat))

    token = login(email=email, api_key=api_key)
    return detect_ai(
        token=token,
        text=text,
        language=None,
        sandbox=False,
        sensitivity=2,
        explain=False,
    )


def extract_ai_rate_from_copyleaks(payload: dict[str, Any]) -> float | None:
    summary = payload.get("summary") or {}
    ai_value = summary.get("ai")
    if isinstance(ai_value, (int, float)):
        return clamp(float(ai_value), 0.0, 1.0)
    return None


def assess_credibility(
    *,
    answer_text: str,
    question_text: str | None,
    in_scope_chunks: list[dict],
    future_chunks: list[dict],
    semantic_index: dict[str, Any],
    ai_rate: float | None,
    ai_source: str | None,
    top_k: int,
    report_top_k: int,
    max_order: int,
) -> dict[str, Any]:
    query_text = "\n".join(part for part in [question_text, answer_text] if part)
    answer_tokens = tokenize_text(answer_text)
    query_tokens = tokenize_text(query_text)

    in_scope_ranked = score_chunks(
        query_text=query_text,
        query_tokens=query_tokens,
        chunks=in_scope_chunks,
        semantic_index=semantic_index,
        top_k=top_k,
    )
    future_ranked = score_chunks(
        query_text=query_text,
        query_tokens=query_tokens,
        chunks=future_chunks,
        semantic_index=semantic_index,
        top_k=top_k,
    )

    top_support = in_scope_ranked[:report_top_k]
    top_future = [item for item in future_ranked if item["combined_score"] > 0][:report_top_k]

    support_coverage = compute_support_coverage(answer_tokens, top_support)
    support_density = compute_support_density(top_support)
    scope_alignment = compute_scope_alignment(top_support, top_future)
    answer_specificity = compute_answer_specificity(answer_text, answer_tokens)
    evidence_consistency = compute_evidence_consistency(top_support)

    base_score = (
        0.38 * support_coverage
        + 0.20 * support_density
        + 0.18 * scope_alignment
        + 0.12 * answer_specificity
        + 0.12 * evidence_consistency
    )
    ai_penalty = 0.18 * ai_rate if ai_rate is not None else 0.0
    final_score = clamp(base_score - ai_penalty, 0.0, 1.0)

    result = {
        "score": round(final_score * 100, 2),
        "label": classify_score(final_score),
        "metrics": {
            "support_coverage": round(support_coverage, 4),
            "support_density": round(support_density, 4),
            "scope_alignment": round(scope_alignment, 4),
            "answer_specificity": round(answer_specificity, 4),
            "evidence_consistency": round(evidence_consistency, 4),
            "ai_rate": None if ai_rate is None else round(ai_rate, 4),
            "ai_penalty": round(ai_penalty, 4),
        },
        "method": {
            "retrieval": "semantic_vector + lexical_overlap",
            "embedding_model": semantic_index["model_name"],
            "semantic_top_k": top_k,
            "ai_source": ai_source,
        },
        "progress_bound": {
            "max_order": max_order,
        },
        "risk_flags": build_risk_flags(
            support_coverage=support_coverage,
            scope_alignment=scope_alignment,
            answer_specificity=answer_specificity,
            evidence_consistency=evidence_consistency,
            ai_rate=ai_rate,
            top_future=top_future,
        ),
        "supporting_chunks": [serialize_ranked_chunk(item) for item in top_support],
        "future_reference_chunks": [serialize_ranked_chunk(item) for item in top_future],
        "answer_preview": shorten(answer_text, 300),
        "question_preview": shorten(question_text or "", 180) if question_text else None,
    }
    return result


def score_chunks(
    *,
    query_text: str,
    query_tokens: set[str],
    chunks: list[dict],
    semantic_index: dict[str, Any],
    top_k: int,
) -> list[dict[str, Any]]:
    if not chunks:
        return []

    allowed_chunk_ids = {chunk["chunk_id"] for chunk in chunks}
    semantic_results = semantic_search(
        query_text=query_text,
        index=semantic_index,
        top_k=min(max(top_k, 1) * 3, len(semantic_index["chunks"])),
    )

    ranked: list[dict[str, Any]] = []
    for item in semantic_results:
        chunk = item["chunk"]
        if chunk["chunk_id"] not in allowed_chunk_ids:
            continue

        chunk_tokens = tokenize_text(chunk["text"])
        overlap = sorted(query_tokens & chunk_tokens)
        lexical_score = 0.0
        if overlap:
            lexical_score = len(overlap) / math.sqrt(max(len(query_tokens), 1) * max(len(chunk_tokens), 1))

        semantic_score = normalize_semantic_score(item["semantic_score"])
        combined_score = 0.7 * semantic_score + 0.3 * clamp(lexical_score * 8.0, 0.0, 1.0)

        ranked.append(
            {
                "chunk": chunk,
                "semantic_score": semantic_score,
                "lexical_score": lexical_score,
                "combined_score": combined_score,
                "overlap": overlap[:20],
            }
        )

    ranked.sort(
        key=lambda item: (
            item["combined_score"],
            item["semantic_score"],
            item["chunk"]["order"],
        ),
        reverse=True,
    )
    return ranked[:top_k]


def normalize_semantic_score(score: float) -> float:
    return clamp((score + 1.0) / 2.0, 0.0, 1.0)


def tokenize_text(text: str) -> set[str]:
    lowered = (text or "").lower()
    tokens: set[str] = set()

    for token in ENGLISH_TOKEN_RE.findall(lowered):
        if len(token) >= 2:
            tokens.add(token)

    for segment in CHINESE_SEGMENT_RE.findall(text or ""):
        segment = segment.strip()
        if not segment:
            continue
        if len(segment) <= 8 and segment not in CHINESE_STOPWORDS:
            tokens.add(segment)
        max_n = min(4, len(segment))
        for n in range(2, max_n + 1):
            for index in range(0, len(segment) - n + 1):
                gram = segment[index:index + n]
                if gram not in CHINESE_STOPWORDS:
                    tokens.add(gram)
    return tokens


def compute_support_coverage(answer_tokens: set[str], ranked_chunks: list[dict]) -> float:
    if not answer_tokens or not ranked_chunks:
        return 0.0
    matched: set[str] = set()
    for item in ranked_chunks:
        matched.update(item["overlap"])
    return len(matched & answer_tokens) / max(len(answer_tokens), 1)


def compute_support_density(ranked_chunks: list[dict]) -> float:
    if not ranked_chunks:
        return 0.0
    weighted = 0.0
    total_weight = 0.0
    for index, item in enumerate(ranked_chunks[:3], start=1):
        weight = 1 / index
        weighted += item["combined_score"] * weight
        total_weight += weight
    return clamp(weighted / max(total_weight, 1e-9), 0.0, 1.0)


def compute_scope_alignment(in_scope_ranked: list[dict], future_ranked: list[dict]) -> float:
    best_in_scope = in_scope_ranked[0]["combined_score"] if in_scope_ranked else 0.0
    best_future = future_ranked[0]["combined_score"] if future_ranked else 0.0
    if best_in_scope <= 0 and best_future <= 0:
        return 0.2
    if best_future <= best_in_scope:
        return 1.0
    ratio = best_future / max(best_in_scope, 0.0001)
    return clamp(1.12 - 0.32 * ratio, 0.0, 1.0)


def compute_answer_specificity(answer_text: str, answer_tokens: set[str]) -> float:
    length_score = clamp(len(answer_text.strip()) / 220.0, 0.0, 1.0)
    token_score = clamp(len(answer_tokens) / 35.0, 0.0, 1.0)
    sentence_count = len([part for part in SENTENCE_SPLIT_RE.split(answer_text) if part.strip()])
    structure_score = clamp(sentence_count / 4.0, 0.0, 1.0)
    return 0.45 * length_score + 0.35 * token_score + 0.2 * structure_score


def compute_evidence_consistency(ranked_chunks: list[dict]) -> float:
    if not ranked_chunks:
        return 0.0
    semantic_avg = sum(item["semantic_score"] for item in ranked_chunks[:3]) / min(len(ranked_chunks), 3)
    overlap_non_empty = sum(1 for item in ranked_chunks[:3] if item["overlap"])
    overlap_ratio = overlap_non_empty / min(len(ranked_chunks), 3)
    return clamp(0.65 * semantic_avg + 0.35 * overlap_ratio, 0.0, 1.0)


def build_risk_flags(
    *,
    support_coverage: float,
    scope_alignment: float,
    answer_specificity: float,
    evidence_consistency: float,
    ai_rate: float | None,
    top_future: list[dict],
) -> list[str]:
    flags: list[str] = []
    if support_coverage < 0.2:
        flags.append("教材支撑较弱")
    elif support_coverage < 0.4:
        flags.append("教材支撑一般")

    if evidence_consistency < 0.45:
        flags.append("证据一致性不足")

    if scope_alignment < 0.45 and top_future and top_future[0]["combined_score"] > 0:
        flags.append("疑似超出当前学习进度")

    if answer_specificity < 0.35:
        flags.append("答案过短或信息密度不足")

    if ai_rate is not None:
        if ai_rate >= 0.8:
            flags.append("AI生成概率较高")
        elif ai_rate >= 0.5:
            flags.append("存在较明显AI参与迹象")

    if not flags:
        flags.append("暂无明显风险")
    return flags


def classify_score(score: float) -> str:
    if score >= 0.8:
        return "高可信"
    if score >= 0.6:
        return "中等可信"
    if score >= 0.4:
        return "存疑"
    return "低可信"


def serialize_ranked_chunk(item: dict[str, Any]) -> dict[str, Any]:
    chunk = item["chunk"]
    return {
        "chunk_id": chunk["chunk_id"],
        "order": chunk["order"],
        "chapter": chunk.get("chapter"),
        "section": chunk.get("section"),
        "topic": chunk.get("topic"),
        "page_start": chunk["page_start"],
        "page_end": chunk["page_end"],
        "semantic_score": round(item["semantic_score"], 4),
        "lexical_score": round(item["lexical_score"], 4),
        "combined_score": round(item["combined_score"], 4),
        "overlap": item["overlap"],
        "snippet": shorten(chunk["text"], 280),
    }


def shorten(text: str, limit: int) -> str:
    text = re.sub(r"\s+", " ", text or "").strip()
    if len(text) <= limit:
        return text
    return text[:limit].rstrip() + "..."


def clamp(value: float, low: float, high: float) -> float:
    return max(low, min(high, value))


def save_json(path: Path, payload: dict[str, Any]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(payload, ensure_ascii=False, indent=2), encoding="utf-8")
    print(f"\nSaved JSON: {path}")


def save_text(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")
    print(f"\nSaved report: {path}")


def build_teacher_report(
    *,
    result: dict[str, Any],
    answer_text: str,
    question_text: str | None,
    llm_model: str | None,
) -> str:
    lines = [
        "# 答案可信度评估报告",
        "",
        "## 一、结论摘要",
        "",
        f"- 综合得分：**{result['score']}**",
        f"- 可信度等级：**{result['label']}**",
        f"- 风险标签：{', '.join(result['risk_flags'])}",
        f"- 评估方法：`{result['method']['retrieval']}`",
        f"- 向量模型：`{result['method']['embedding_model']}`",
        f"- AI率来源：`{result['method']['ai_source'] or '未提供'}`",
        "",
        "## 二、问题与答案",
        "",
    ]
    if question_text:
        lines.extend(["### 题目", "", question_text.strip(), ""])
    lines.extend(["### 学生答案", "", answer_text.strip(), ""])

    lines.extend(["## 三、量化指标", ""])
    for key, value in result["metrics"].items():
        lines.append(f"- {key}: `{value}`")

    lines.extend(["", "## 四、教材支撑证据", ""])
    support_chunks = result.get("supporting_chunks") or []
    if support_chunks:
        for item in support_chunks:
            title = " / ".join(
                part for part in [item.get("chapter"), item.get("section"), item.get("topic")] if part
            ) or "未识别标题"
            lines.extend(
                [
                    f"### {item['chunk_id']} | {title}",
                    "",
                    f"- pages: `{item['page_start']}-{item['page_end']}`",
                    f"- semantic_score: `{item['semantic_score']}`",
                    f"- lexical_score: `{item['lexical_score']}`",
                    f"- combined_score: `{item['combined_score']}`",
                    f"- overlap: {', '.join(item.get('overlap') or [])}",
                    "",
                    item["snippet"],
                    "",
                ]
            )
    else:
        lines.extend(["未找到明显教材支撑片段。", ""])

    future_chunks = result.get("future_reference_chunks") or []
    lines.extend(["## 五、超纲风险检查", ""])
    if future_chunks:
        lines.append("以下片段位于当前学习进度之后，但与答案仍然有一定相关性：")
        lines.append("")
        for item in future_chunks:
            title = " / ".join(
                part for part in [item.get("chapter"), item.get("section"), item.get("topic")] if part
            ) or "未识别标题"
            lines.extend(
                [
                    f"### {item['chunk_id']} | {title}",
                    "",
                    f"- pages: `{item['page_start']}-{item['page_end']}`",
                    f"- combined_score: `{item['combined_score']}`",
                    "",
                    item["snippet"],
                    "",
                ]
            )
    else:
        lines.extend(["未发现明显超出当前进度的高相关教材片段。", ""])

    lines.extend(
        [
            "## 六、教师建议",
            "",
            build_teacher_recommendation(result),
            "",
        ]
    )

    ai_summary = build_llm_summary(
        result=result,
        answer_text=answer_text,
        question_text=question_text,
        llm_model=llm_model,
    )
    if ai_summary:
        lines.extend(["## 七、AI辅助评语", "", ai_summary, ""])

    return "\n".join(lines)


def build_teacher_recommendation(result: dict[str, Any]) -> str:
    if result["label"] == "高可信":
        return "建议将该答案视为教材范围内的高可信回答，可重点核查表述是否完整、是否有少量措辞偏差。"
    if result["label"] == "中等可信":
        return "建议人工复核前 3 个支撑教材片段，确认答案是否准确复述了课本内容，并检查是否存在少量超纲扩展。"
    if result["label"] == "存疑":
        return "建议结合学生当前学习进度和课堂表现复核该答案，重点检查答案中的关键术语是否来自当前章节。"
    return "建议重点人工核查。当前答案的教材支撑度偏弱，或 AI 参与迹象较高，不能直接作为高可信学习结果使用。"


def build_llm_summary(
    *,
    result: dict[str, Any],
    answer_text: str,
    question_text: str | None,
    llm_model: str | None,
) -> str | None:
    if not llm_model:
        return None

    backend_dir = Path(__file__).resolve().parents[1] / "backend"
    if str(backend_dir) not in sys.path:
        sys.path.insert(0, str(backend_dir))
    try:
        from app.llm_service import generate_completion
    except Exception as exc:
        return f"AI评语生成失败：无法加载模型服务，{exc}"

    prompt = (
        "你是教师端评估助手。请根据下面的结构化结果，生成一段正式、克制的中文教师评语。"
        "评语必须覆盖：1）教材支撑是否充分；2）是否疑似超纲；3）AI参与风险；4）教师下一步建议。"
        "不要编造信息，控制在220字以内。\n\n"
        f"问题：{question_text or '未提供'}\n"
        f"答案：{answer_text}\n"
        f"评估结果：{json.dumps(result, ensure_ascii=False)}"
    )
    try:
        completion = generate_completion(model_key=llm_model, prompt=prompt, history_messages=[])
        return completion["content"].strip()
    except Exception as exc:
        return f"AI评语生成失败：{exc}"


def print_summary(result: dict[str, Any]) -> None:
    print("Credibility summary:")
    print(f"- score: {result['score']}")
    print(f"- label: {result['label']}")
    for key, value in result["metrics"].items():
        print(f"- {key}: {value}")
    print(f"- risk_flags: {', '.join(result['risk_flags'])}")
    if result["supporting_chunks"]:
        print("- top supporting chunks:")
        for item in result["supporting_chunks"][:3]:
            title = " / ".join(
                part for part in [item.get("chapter"), item.get("section"), item.get("topic")] if part
            ) or "未识别标题"
            print(f"  - {item['chunk_id']} | {title} | combined_score={item['combined_score']}")


if __name__ == "__main__":
    raise SystemExit(main())
