import argparse
from pathlib import Path

from kb_semantic_retriever import DEFAULT_EMBEDDING_MODEL, build_or_load_index


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Build a semantic vector index for textbook KB.")
    parser.add_argument(
        "--kb-dir",
        default="test/textbook_kb",
        help="Directory generated by textbook_to_kb.py.",
    )
    parser.add_argument(
        "--model",
        default=DEFAULT_EMBEDDING_MODEL,
        help="Embedding model name from Hugging Face.",
    )
    parser.add_argument(
        "--force",
        action="store_true",
        help="Rebuild the vector index even if cached files already exist.",
    )
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    root = Path(__file__).resolve().parents[1]
    kb_dir = (root / args.kb_dir).resolve()
    index = build_or_load_index(
        kb_dir=kb_dir,
        model_name=args.model,
        force_rebuild=args.force,
    )
    print(f"KB directory: {kb_dir}")
    print(f"Model: {index['model_name']}")
    print(f"Chunks: {len(index['chunks'])}")
    print(f"Embedding shape: {index['embeddings'].shape}")
    print(f"Index directory: {index['index_dir']}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
