import argparse
import json
from pathlib import Path


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Filter ordered textbook KB by learning progress.")
    parser.add_argument(
        "--kb-dir",
        default="test/textbook_kb",
        help="Directory generated by textbook_to_kb.py",
    )
    parser.add_argument(
        "--max-order",
        type=int,
        default=None,
        help="Keep chunks with order <= max-order.",
    )
    parser.add_argument(
        "--chapter",
        default=None,
        help='Keep chunks up to and including this chapter, e.g. "第二章 算法与程序实现".',
    )
    parser.add_argument(
        "--section",
        default=None,
        help='Optional section bound inside the chosen chapter, e.g. "第二节 程序设计语言基本知识".',
    )
    parser.add_argument(
        "--preview",
        type=int,
        default=5,
        help="How many matching chunks to preview.",
    )
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    root = Path(__file__).resolve().parents[1]
    kb_dir = (root / args.kb_dir).resolve()
    chunks = load_jsonl(kb_dir / "kb_chunks.jsonl")
    outline = json.loads((kb_dir / "outline.json").read_text(encoding="utf-8"))

    max_order = resolve_max_order(args, chunks, outline)
    filtered = [chunk for chunk in chunks if chunk["order"] <= max_order]

    print(f"Max order: {max_order}")
    print(f"Available chunks: {len(filtered)}")
    for chunk in filtered[: args.preview]:
        title = " / ".join(
            part for part in [chunk.get("chapter"), chunk.get("section"), chunk.get("topic")] if part
        ) or "未识别标题"
        print(f"- {chunk['chunk_id']} | {title} | 页 {chunk['page_start']}-{chunk['page_end']}")
        print(f"  {chunk['text'][:180].replace(chr(10), ' ')}")

    return 0


def resolve_max_order(args: argparse.Namespace, chunks: list[dict], outline: list[dict]) -> int:
    if args.max_order is not None:
        return args.max_order

    if not args.chapter:
        return max(chunk["order"] for chunk in chunks)

    target_first_page = None
    for item in outline:
        if item["chapter"] != args.chapter:
            continue
        if args.section and item.get("section") != args.section:
            continue
        target_first_page = item["last_page"]

    if target_first_page is None:
        raise SystemExit("Could not find the requested chapter/section in outline.json")

    eligible = [chunk["order"] for chunk in chunks if chunk["page_end"] <= target_first_page]
    if not eligible:
        raise SystemExit("No chunks matched the requested progress bound")
    return max(eligible)


def load_jsonl(path: Path) -> list[dict]:
    rows: list[dict] = []
    with path.open("r", encoding="utf-8") as fh:
        for line in fh:
            line = line.strip()
            if line:
                rows.append(json.loads(line))
    return rows


if __name__ == "__main__":
    raise SystemExit(main())
