SELECT 'CREATE DATABASE aigc_platform'
WHERE NOT EXISTS (
  SELECT 1 FROM pg_database WHERE datname = 'aigc_platform'
)\gexec

\connect aigc_platform

DO $$
BEGIN
  CREATE TYPE userrole AS ENUM ('student', 'teacher');
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

CREATE TABLE IF NOT EXISTS users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  account VARCHAR(64) NOT NULL UNIQUE,
  name VARCHAR(64) NOT NULL,
  role userrole NOT NULL,
  password_hash VARCHAR(255) NOT NULL,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_users_role ON users (role);

CREATE TABLE IF NOT EXISTS assignments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  teacher_id BIGINT NOT NULL,
  title VARCHAR(120) NOT NULL,
  description TEXT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_assignments_teacher_id FOREIGN KEY (teacher_id) REFERENCES users(id)
);

CREATE INDEX IF NOT EXISTS idx_assignments_teacher_id ON assignments (teacher_id);

CREATE TABLE IF NOT EXISTS chat_conversations (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL,
  assignment_id BIGINT NULL,
  title VARCHAR(120) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_chat_conversations_user_id FOREIGN KEY (user_id) REFERENCES users(id),
  CONSTRAINT fk_chat_conversations_assignment_id FOREIGN KEY (assignment_id) REFERENCES assignments(id)
);

CREATE INDEX IF NOT EXISTS idx_chat_conversations_user_id ON chat_conversations (user_id);
CREATE INDEX IF NOT EXISTS idx_chat_conversations_assignment_id ON chat_conversations (assignment_id);
CREATE INDEX IF NOT EXISTS idx_chat_conversations_updated_at ON chat_conversations (updated_at);

CREATE TABLE IF NOT EXISTS chat_records (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL,
  conversation_id BIGINT NULL,
  model_name VARCHAR(64) NOT NULL,
  generated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  prompt TEXT NOT NULL,
  content TEXT NOT NULL,
  citations JSONB NOT NULL DEFAULT '[]'::jsonb,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_chat_records_user_id FOREIGN KEY (user_id) REFERENCES users(id),
  CONSTRAINT fk_chat_records_conversation_id FOREIGN KEY (conversation_id) REFERENCES chat_conversations(id)
);

CREATE INDEX IF NOT EXISTS idx_chat_user_id ON chat_records (user_id);
CREATE INDEX IF NOT EXISTS idx_chat_conversation_id ON chat_records (conversation_id);
CREATE INDEX IF NOT EXISTS idx_chat_generated_at ON chat_records (generated_at);

CREATE TABLE IF NOT EXISTS answer_submissions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL,
  conversation_id BIGINT NOT NULL UNIQUE,
  answer_text TEXT NOT NULL,
  source_filename VARCHAR(255) NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_answer_submissions_user_id FOREIGN KEY (user_id) REFERENCES users(id),
  CONSTRAINT fk_answer_submissions_conversation_id FOREIGN KEY (conversation_id) REFERENCES chat_conversations(id)
);

CREATE INDEX IF NOT EXISTS idx_answer_submissions_user_id ON answer_submissions (user_id);
CREATE INDEX IF NOT EXISTS idx_answer_submissions_conversation_id ON answer_submissions (conversation_id);
